### ISSUE TITLE
[UI core library] Button width limit

### ISSUE THREAD

**Issue by jozefhruska** [hazelcast/frontend-shared#101]
Currently `<Button />` is limited to `max-width: 300px`. On Cloud we need at least 370px:

![image.png](https://images.zenhubusercontent.com/5d08cfacfa8bce0a6ea35f38/b1590169-4f26-4b67-9453-f9967eb5ae84)

Should we either remove limit entirely or just set it to 270 or more? WDYT?

**Comment by jvorcak** [comment]
I agree it should go away. As for my self I see no reason for such a value.
