### ISSUE TITLE
[UI core library] Select isn't SSR compatible

### ISSUE THREAD

**Issue by jozefhruska** [hazelcast/frontend-shared#107]
It seems like there's an issue with Select on SSR:
![image.png](https://images.zenhubusercontent.com/5d08cfacfa8bce0a6ea35f38/63e38b1e-f3d4-40df-9673-5f2028d26723)

This is caused by this method (document is not defined during server side render):
```ts
const getMenuContainer = (menuPortalTarget: 'body' | 'self' | HTMLElement | null): HTMLElement | null | undefined => {
  if (menuPortalTarget == 'body') {
    return document.body
  }
  if (menuPortalTarget == 'self') {
    return undefined
  }
  return menuPortalTarget
}
```

Currently this is a blocker for the new Cloud sign up.

**Comment by aigoncharov** [comment]
@jozefhruska you can passing a custom menuPortalTarget as a workaround. I'll try to work on the fix tomorrow.
