### ISSUE TITLE
Changes to Link component

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/frontend-shared#110]
Next uses it's own `Link` component which improves the performance of a page transitions. And we need to use it for our app.

https://nextjs.org/docs/api-reference/next/link

Now there are 3 problems, but before I mention them I need to suggest our implementation (do not mind that the solution is not fully typed, it's just a prototype for now)

```

type HazelcastLinkProps = {
  href: string,
} // tmp until it's exported

const NextLinkForwardRef = React.forwardRef(({ onClick, href, ...props }: HazelcastLinkProps, ref) => {
  // https://nextjs.org/docs/api-reference/next/link

  // This works smoothly
  return <a href={href} ref={ref} onClick={onClick} rel="noopener">Click me</a>

  // This doesn't work - refreshes the page
  // return <a href={href} ref={ref}>Click me</a>

  // Proposed solution
  // return (
  //   <HazelcastLink href={href} onClick={onClick} rel="noopener" target="_self" {...props}>
  //     Click Me
  //   </HazelcastLink>
  // )
})

const NextLink = ({ href, ...props }: HazelcastLinkProps) => (
  <Link href={href} passHref>
    <NextLinkForwardRef {...props}/>
  </Link>
)
```

Usage:
```<NextLink href="/sign-in">Back to /sign-in</NextLink>```

What we need to do:

1. Pass `onClick` property to a link, without it Next.js is shorthanded. As you can see, I've tried with `<a>` attribute
2. We would need to export types (possibly not only for this component, it'll be useful when wrapping our components in the stacks). This is one scenario, another one I can think about is re-using `Label` e.g. for card input on .cloud. I think it's pretty common to export types, I can make another issue for that.
3. nit: what confused me a bit is that we have default `target='blank'` and `rel='noopener noreferrer'`. I don't think we should have that (except `noopener`) + I don't think this is the same discussion as it was about restricting developers to best practices, this is more about what is more common to have as default. On .cloud, `noreferrer` could potentially break some GA data tracking, and `target=blank` is rarely used if ever. Most of the UIs actually want to opposite as it's now. But again, if you insist, we can set our values in our wrapper. 

Please let me know what you think and I can make a PR @aigoncharov @jankoritak @danad02 @jozefhruska @utkukaratas

**Comment by jozefhruska** [comment]
I agree with with all 3 points. I didn't found any other workaround for this :/

**Comment by aigoncharov** [comment]
@jvorcak @jozefhruska now you should have the API to build the NextJS abstraction for Cloud
