### ISSUE TITLE
Double tooltip shown for a button

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/frontend-shared#132]
![Screenshot 2020-12-19 at 15 44 20](https://user-images.githubusercontent.com/1083817/102692076-4c7bef80-4211-11eb-9e5a-008d15d5316a.png)

Hi,

I've discovered this during development, before I managed to reserve more space for the button.

Consider a button that has truncated text and is disabled in the same time. We should try to avoid showing 2 tooltips at once.

**Comment by aigoncharov** [comment]
@jvorcak I suggest we should only the disabled tooltip. WDYT?
