### ISSUE TITLE
[UI core library] Multiselect

### ISSUE THREAD

**Issue by aigoncharov** [hazelcast/frontend-shared#15]
https://zeroheight.com/11d0e6dac/p/746b74-multiselect

1. Create a library-agnostic component
    1. API (extend https://formik.org/docs/api/useField#fieldinputpropsvalue)
        1. name
        2. value
        3. onChange
        4. onBlur
        5. label
        6. error
        7. touched
        8. options (as children)
2. Create a formik v2 wrapper

**Comment by utkukaratas** [comment]
i volunteer to take this on. i dabbled in several different versions of this component in several different frameworks and there was not one of them i did not swear at. let me see if i can do better. nice challange.

**Comment by aigoncharov** [comment]
@utkukaratas sure, why not. Feel free to pick it up after the `Toggle`

**Comment by aigoncharov** [comment]
@utkukaratas please, with with @pawelklasa to get the design for the multiselect finalized. 
As to the implementation, I suggest you start with copying what we have for Select and building on top of it.

**Comment by utkukaratas** [comment]
@aigoncharov  my plan exactly. btw i see that everything is based on react-select so that makes the job much easier. (i thought we were doing core-ui from scratch)

**Comment by aigoncharov** [comment]
@utkukaratas we are free to use any libraries we want as long as their usage is justified. Small list of dependencies is not a purpose, it is a tool to get smaller bundle size.
