### ISSUE TITLE
Make storybook work in IE11

### ISSUE THREAD

**Issue by aigoncharov** [hazelcast/frontend-shared#28]
Maybe, try this https://github.com/storybookjs/storybook/issues/9242#issuecomment-693884172

**Comment by jvorcak** [comment]
I made it work by including `require('core-js/stable')` for IE in `manager.js`

However I can't still make it work for any module importing from '@hazelcast/services' -> TextField + Checkbox which uses logger from that module in a storybook.

Any hints guys? @aigoncharov @danad02 @jankoritak @jozefhruska

**Comment by aigoncharov** [comment]
@jvorcak I would try several things:
- Replace `Map` with `{}` as Maps have limited support in IE11
- Try commenting out the parts with `Object.entries` and `Object.values`. See if that API is the reason for the failure.
- Try removing `serialize-error`. See if it is the reason for the failure.
