### ISSUE TITLE
[UI core library] Radio button

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/frontend-shared#44]
https://www.figma.com/file/8mVm6LTbp2Z0RaWWjTZoft/%F0%9F%90%9DHIVE---Hazelcast-Design-System?node-id=479%3A273

1. Create a library-agnostic component, similar to Checkbox implementation.

2. Create a formik v2 wrapper

**Comment by jvorcak** [comment]
Put un hold, until there are designs in Figma

**Comment by aigoncharov** [comment]
Closed by https://github.com/hazelcast/frontend-shared/pull/54
