### ISSUE TITLE
Outline of the button should be aligned with the button

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/frontend-shared#80]
<img width="596" alt="Screenshot 2020-11-19 at 15 03 38" src="https://user-images.githubusercontent.com/1083817/99676190-7a3a1100-2a78-11eb-89b3-55327e12adb6.png">
<img width="716" alt="Screenshot 2020-11-19 at 15 03 36" src="https://user-images.githubusercontent.com/1083817/99676196-7ad2a780-2a78-11eb-90d8-ba2bb568b25e.png">

I assume we want outline of a button to align with it's border so that it looks consistent with other components?

**Comment by jankoritak** [comment]
This is intended behaviour.

Source: https://www.figma.com/file/8mVm6LTbp2Z0RaWWjTZoft/%F0%9F%90%9DHIVE---Hazelcast-Design-System?node-id=1491%3A295

**Comment by jvorcak** [comment]
asd

**Comment by jvorcak** [comment]
@pawelklasa feel free to close if this is intended.
