### ISSUE TITLE
[UI core library] Box

### ISSUE THREAD

**Issue by jozefhruska** [hazelcast/frontend-shared#81]
"Helper" component for creating basic layouts, inspired by MD's `Box` (https://material-ui.com/system/basics/#object).

API proposal:
https://styled-system.com/api

**Comment by utkukaratas** [comment]
IMHO any ready made layout components or grids are a thing of past. 

They were fine in the Bootstrap 1-2-3 era where "clear: both" was a thing and there were no flexbox or css grid support to speak of.

Today we have flexbox&grid in every modernish browser. So i think most a framework should give to the developers regarding layouts could be utility classes related to flexbox/margins/padding a la tachyons or basscss. Just my two cents.

**Comment by jvorcak** [comment]
@utkukaratas Box component is used in quite a lot of systems and provides helpers also for flexbox/grid, I don't think this pattern contradicts anything you mention and it's used in Styled-component based systems, and quite a lot of libs e.g. Material UI.

----

However, we have made a good decision to use tailwindcss with their utility classes, which should close this issue and also satisfy your request. I also find it much better and more flexible than `Box` abstraction.
