### ISSUE TITLE
Replace useRef(uuid()) with react-uid

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/frontend-shared#86]
Problem when using our lib with SSR:

<img width="1180" alt="Screenshot 2020-11-24 at 12 02 15" src="https://user-images.githubusercontent.com/1083817/100085884-e76cee00-2e4c-11eb-8d48-63402197b190.png">

Basically `useRef(uuid())` generates different string on a server compared to the client.

One possible solution:

Use: https://github.com/thearnica/react-uid
Related article: https://medium.com/@antonkorzunov/an-easy-way-to-name-labels-and-generate-unique-keys-5ec2f9667e6a

API would look like this

```
const uuid = useUID();

<label htmlFor={uuid} .... />
```

And all SSR rendered apps or tests would need to wrap the app with `<UIDReset>` from this lib. Client side only apps would need to do probably nothing.

https://github.com/thearnica/react-uid/blob/master/src/Control.tsx#L10

I've had a look at the source code of the lib and it seems reasonable, it's ~900B big. WDYT?

I'm open to other suggestions as well. cc @aigoncharov @jankoritak @jozefhruska @danad02

**Comment by aigoncharov** [comment]
I like the solution but I would like to spend some time on the research. Nowadays, everybody does SSR, why this lib has so little stars? Everyone who cares even a little about a11y should face the same problem and should somehow solve it. I am wondering how.

**Comment by aigoncharov** [comment]
@jvorcak I did a small research. It seems there won't be any viable solution from the react team soon (https://github.com/facebook/react/issues/5867#issuecomment-678267054), so I suggest we do what you proposed - try `react-uid`.

**Comment by jvorcak** [comment]
GJ @aigoncharov
