### ISSUE TITLE
Make Link component inline

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/frontend-shared#94]
Would it be please possible to use `display: inline-flex` for `Link` component so that we can use it regularly as `<a>` element? I'd be quite useful I think. WDYT? @danad02 @aigoncharov 

Right now it's `display: flex` and it doesn't allow us to easily use it inline without further styling.

e.g 
![Screenshot 2020-11-25 at 14 33 43](https://user-images.githubusercontent.com/1083817/100234365-46a13000-2f2b-11eb-83e0-fa9e1865c282.png)

**Comment by aigoncharov** [comment]
@jvorcak makes total sense to me. Go ahead.

**Comment by aigoncharov** [comment]
Closed by #96
