### ISSUE TITLE
[UI core library] Secondary (footer) link type

### ISSUE THREAD

**Issue by jozefhruska** [hazelcast/frontend-shared#97]
We need to implement secondary link type for Cloud (footer links on design below):
https://www.figma.com/file/kaC3jgqMSgqMEgnv7TIse1/%F0%9F%93%90Sign-in-flow?node-id=1350%3A1962

**Comment by aigoncharov** [comment]
@utkukaratas I suggest we add a `kind` prop with two values: 'primary' and `secondary`, and assign classes based on them.
