### ISSUE TITLE
Change component as parameter API

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/frontend-shared#98]
I think it's good practice to let upper component to provide component instance instead of a component itself. We will be able to pass more parameters in a future. This is just one of the examples where this could be useful.

```
<Button type="submit" iconLeft={Loader} iconLeftAriaLabel="Loading ...">Sign in</Button>
```

```
<Button type="submit" iconLeft={<Loader className="animate-spin-slow" />} iconLeftAriaLabel="Loading ...">Sign in</Button>
```

WDYT @jankoritak @aigoncharov @jozefhruska @danad02

**Comment by jozefhruska** [comment]
@jvorcak Do we need it somewhere currently? If not, I'd prefer the first (current) variant.

**Comment by jvorcak** [comment]
<img width="574" alt="Screenshot 2020-11-27 at 15 13 18" src="https://user-images.githubusercontent.com/1083817/100457867-17bdc200-30c3-11eb-9a19-b2676e776b9f.png">

@jozefhruska

**Comment by aigoncharov** [comment]
@jvorcak we had this discussion in scope of the initial `Button` PR - https://github.com/hazelcast/management-center/pull/3938#discussion_r501717080
I feel it is a never-ending debate over how much freedom developers should have. Stricter APIs tend to result in more consistent UIs.
I would suggest to leave the API as is as it should allow you to solve your use-case - take a look at `iconLeftClassName`.

**Comment by jvorcak** [comment]
@aigoncharov I've totally missed that one sorry.
