### ISSUE TITLE
[UI core library] Update Checkbox label type

### ISSUE THREAD

**Issue by jozefhruska** [hazelcast/frontend-shared#99]
On Cloud we need to have a link in the label of checkbox:
![image.png](https://images.zenhubusercontent.com/5d08cfacfa8bce0a6ea35f38/8ee183d0-0106-4714-856d-f72012b98308)

Currently it accepts only `string`, I'd suggest to change it to `ReactNode` instead.

**Comment by jvorcak** [comment]
LGTM, I'll update it soon.
